import { CuratedCourse } from "./types";

export const curatedCourses: CuratedCourse[] = [
  {
    id: "course-1",
    title: "성수동 감성 데이트",
    subtitle: "힙한 카페와 갤러리를 돌며 사진 찍기 좋은 코스",
    coverGradient: "from-orange-400 to-pink-500",
    coverEmoji: "🎨",
    area: "성수동",
    tags: ["감성", "카페", "사진"],
    rating: 4.8,
    reviewCount: 324,
    price: 0,
    isPremium: false,
    reviews: [
      { id: "r1", nickname: "민지", rating: 5, comment: "서울숲 산책이 최고였어요! 사슴도 보고 벤치에서 수다도 떨고 완벽한 하루!", date: "2026-03-15" },
      { id: "r2", nickname: "준혁", rating: 4, comment: "카페 오르에르 루프탑 뷰가 진짜 대박이에요. 줄이 좀 있긴 한데 가치 있음", date: "2026-03-10" },
      { id: "r3", nickname: "소연", rating: 5, comment: "대림창고부터 뚝섬까지 동선이 완벽해요. 사진 찍을 곳도 많고!", date: "2026-02-28" },
    ],
    timetable: [
      { time: "11:00", duration: "1시간", activity: "대림창고 갤러리 관람", category: "culture", cost: "무료", tip: "주말엔 줄 서니 오전에 가세요" },
      { time: "12:00", duration: "1시간", activity: "성수 수제버거 맛집에서 런치", category: "meal", cost: "약 2만원", tip: "어니언 버거 추천, 웨이팅 15분" },
      { time: "13:30", duration: "1시간", activity: "카페 오르에르 루프탑에서 커피", category: "cafe", cost: "약 1만원", tip: "루프탑석 일찍 가서 확보하세요" },
      { time: "15:00", duration: "1시간 30분", activity: "서울숲 산책 + 벤치에서 수다", category: "walk", cost: "무료", tip: "사슴방사장 쪽이 한적해요" },
      { time: "17:00", duration: "1시간", activity: "뚝섬 포토존에서 인생샷 찍기", category: "photo", cost: "무료", tip: "해질녘 골든아워가 최고!" },
      { time: "18:30", duration: "1시간 30분", activity: "성수동 파스타 맛집에서 디너", category: "meal", cost: "약 3만원", tip: "오레키에테 파스타 강추" },
    ],
  },
  {
    id: "course-2",
    title: "을지로 레트로 탐험",
    subtitle: "힙지로 감성 뿜뿜! 숨은 맛집과 바 투어",
    coverGradient: "from-amber-500 to-orange-600",
    coverEmoji: "🏚️",
    area: "을지로",
    tags: ["레트로", "맛집", "밤"],
    rating: 4.6,
    reviewCount: 198,
    price: 0,
    isPremium: false,
    reviews: [
      { id: "r4", nickname: "태윤", rating: 5, comment: "을지로 골목 분위기가 진짜 독특해요. 사진 찍기 좋은 곳이 많아서 좋았음", date: "2026-03-12" },
      { id: "r5", nickname: "하은", rating: 4, comment: "숨은 바 투어가 진짜 재밌었어요! 예약 안 되니까 일찍 가는 게 포인트", date: "2026-03-05" },
    ],
    timetable: [
      { time: "14:00", duration: "1시간", activity: "을지로 골목 탐험 + 벽화 사진", category: "walk", cost: "무료", tip: "세운상가 옥상 뷰가 숨겨진 명소!" },
      { time: "15:30", duration: "1시간", activity: "레트로 다방에서 쌍화차", category: "cafe", cost: "약 8천원", tip: "을지다방 추천, 인테리어가 레트로 그 자체" },
      { time: "17:00", duration: "1시간 30분", activity: "을지로 노포 맛집에서 저녁", category: "meal", cost: "약 2만원", tip: "양미옥 설렁탕 또는 을지면옥 냉면" },
      { time: "19:00", duration: "1시간", activity: "을지로 골목 야경 산책", category: "walk", cost: "무료", tip: "네온 간판들이 밤에 더 분위기 있어요" },
      { time: "20:00", duration: "2시간", activity: "숨은 바에서 칵테일 투어", category: "cafe", cost: "약 3만원", tip: "문열기 앞에 줄서야 입장 가능" },
    ],
  },
  {
    id: "course-3",
    title: "한강 피크닉 데이트",
    subtitle: "여유롭게 치킨 시켜놓고 한강 뷰 즐기기",
    coverGradient: "from-green-400 to-emerald-500",
    coverEmoji: "🌿",
    area: "여의도/한강",
    tags: ["야외", "피크닉", "힐링"],
    rating: 4.7,
    reviewCount: 456,
    price: 0,
    isPremium: false,
    reviews: [
      { id: "r6", nickname: "서현", rating: 5, comment: "날씨 좋은 날 한강 피크닉은 진리! 자전거 타고 선유도까지 가니까 완벽했어요", date: "2026-03-18" },
      { id: "r7", nickname: "지훈", rating: 5, comment: "노을 타임에 맞춰서 간 게 신의 한 수. 인생 사진 건졌어요 ㅋㅋ", date: "2026-03-08" },
    ],
    timetable: [
      { time: "11:00", duration: "30분", activity: "편의점에서 간식 & 음료 장보기", category: "shopping", cost: "약 2만원", tip: "돗자리는 다이소에서 미리 사세요" },
      { time: "11:30", duration: "30분", activity: "여의도 한강공원 명당 자리 잡기", category: "walk", cost: "무료", tip: "나무 그늘 아래가 최고의 자리" },
      { time: "12:00", duration: "2시간", activity: "피크닉 + 배달 치킨으로 런치", category: "meal", cost: "약 2만원", tip: "배달앱에서 한강공원 배달 가능 확인!" },
      { time: "14:00", duration: "1시간 30분", activity: "따릉이 대여해서 자전거 라이딩", category: "activity", cost: "약 3천원", tip: "따릉이 앱 미리 설치 + 결제 등록" },
      { time: "16:00", duration: "1시간", activity: "선유도 공원 산책 & 사진", category: "walk", cost: "무료", tip: "온실 정원이 포토스팟!" },
      { time: "17:30", duration: "1시간", activity: "한강 노을 감상 + 인생샷", category: "rest", cost: "무료", tip: "해질녘 30분 전부터 자리 잡으세요" },
      { time: "19:00", duration: "1시간", activity: "여의도 맛집에서 저녁 식사", category: "meal", cost: "약 3만원", tip: "더현대 지하 푸드코트도 좋아요" },
    ],
  },
  {
    id: "course-4",
    title: "프리미엄 오마카세 데이트",
    subtitle: "특별한 날을 위한 풀코스 파인다이닝",
    coverGradient: "from-yellow-400 to-amber-500",
    coverEmoji: "👑",
    area: "청담/도산",
    tags: ["프리미엄", "오마카세", "특별한 날"],
    rating: 4.9,
    reviewCount: 87,
    price: 3900,
    isPremium: true,
    reviews: [
      { id: "r8", nickname: "수빈", rating: 5, comment: "기념일에 여기 코스 그대로 따라갔는데 여자친구가 감동받았어요! 가격은 좀 하지만...", date: "2026-03-20" },
      { id: "r9", nickname: "예은", rating: 5, comment: "플라워 카페부터 오마카세, 루프탑 바까지... 완벽한 하루였어요", date: "2026-02-14" },
    ],
    timetable: [
      { time: "15:00", duration: "1시간", activity: "도산공원 산책하며 분위기 전환", category: "walk", cost: "무료", tip: "벤치에 앉아 도란도란 이야기하기" },
      { time: "16:00", duration: "1시간", activity: "청담동 플라워 카페에서 디저트", category: "cafe", cost: "약 1.5만원", tip: "플라워 라떼가 포토제닉!" },
      { time: "17:30", duration: "30분", activity: "청담 편집숍에서 윈도우 쇼핑", category: "shopping", cost: "무료", tip: "구경만 해도 눈이 즐거워요" },
      { time: "18:30", duration: "2시간", activity: "오마카세 코스 디너", category: "meal", cost: "약 15만원", tip: "최소 2주 전 예약 필수! 카운터석 추천" },
      { time: "21:00", duration: "1시간 30분", activity: "루프탑 바에서 야경 + 칵테일", category: "cafe", cost: "약 5만원", tip: "자리 예약 가능한 곳 미리 알아보세요" },
    ],
  },
  {
    id: "course-5",
    title: "홍대/연남동 힙투어",
    subtitle: "트렌디한 맛집과 독특한 가게들 탐방",
    coverGradient: "from-purple-400 to-fuchsia-500",
    coverEmoji: "🎸",
    area: "홍대/연남동",
    tags: ["트렌디", "맛집", "문화"],
    rating: 4.5,
    reviewCount: 278,
    price: 0,
    isPremium: false,
    reviews: [
      { id: "r10", nickname: "도윤", rating: 4, comment: "연남동 경의선숲길 산책이 좋았어요. 주말엔 좀 붐비지만 평일엔 여유로움", date: "2026-03-14" },
      { id: "r11", nickname: "유나", rating: 5, comment: "독립서점 구경하고 빈티지 가게 돌아다니는 게 너무 재밌었어요!", date: "2026-03-01" },
    ],
    timetable: [
      { time: "11:30", duration: "1시간", activity: "연남동 브런치 카페에서 식사", category: "meal", cost: "약 2만원", tip: "토스트 전문점이 웨이팅 짧아요" },
      { time: "13:00", duration: "1시간", activity: "경의선숲길 산책 + 벤치 휴식", category: "walk", cost: "무료", tip: "벚꽃 시즌엔 여기가 서울 최고" },
      { time: "14:00", duration: "1시간", activity: "독립서점 & 빈티지샵 구경", category: "shopping", cost: "약 1만원", tip: "땡스북스, 스토리지북앤필름 추천" },
      { time: "15:30", duration: "1시간", activity: "홍대 핫플 디저트 카페", category: "cafe", cost: "약 1.2만원", tip: "크로플 맛집은 인스타 검색!" },
      { time: "17:00", duration: "1시간", activity: "홍대 놀이터 거리 구경", category: "walk", cost: "무료", tip: "버스킹 공연이 있으면 강추!" },
      { time: "18:30", duration: "1시간 30분", activity: "홍대 이자카야에서 저녁", category: "meal", cost: "약 4만원", tip: "골목 안쪽 작은 가게들이 맛집" },
      { time: "20:30", duration: "1시간 30분", activity: "보드게임 카페에서 마무리", category: "activity", cost: "약 1만원", tip: "2인용 게임 추천받으세요" },
    ],
  },
  {
    id: "course-6",
    title: "경복궁/북촌 한옥 코스",
    subtitle: "한복 입고 전통 감성 물씬 느끼기",
    coverGradient: "from-red-400 to-rose-500",
    coverEmoji: "🏯",
    area: "종로/북촌",
    tags: ["전통", "한옥", "사진"],
    rating: 4.7,
    reviewCount: 312,
    price: 0,
    isPremium: false,
    reviews: [
      { id: "r12", nickname: "채원", rating: 5, comment: "한복 입고 경복궁 무료 입장! 사진 진짜 예쁘게 나와요", date: "2026-03-16" },
      { id: "r13", nickname: "건우", rating: 4, comment: "북촌 한옥마을 골목이 분위기 최고. 조용한 카페도 많아요", date: "2026-03-02" },
    ],
    timetable: [
      { time: "10:00", duration: "1시간", activity: "한복 대여하고 변신!", category: "shopping", cost: "약 2만원", tip: "경복궁 근처 한복 대여점 미리 예약" },
      { time: "11:00", duration: "2시간", activity: "경복궁 관람 + 포토타임", category: "culture", cost: "무료 (한복 착용 시)", tip: "근정전 앞이 최고의 포토스팟" },
      { time: "13:00", duration: "1시간", activity: "삼청동 맛집에서 점심", category: "meal", cost: "약 2만원", tip: "삼청동 수제비 골목 추천" },
      { time: "14:30", duration: "1시간 30분", activity: "북촌 한옥마을 골목 산책", category: "walk", cost: "무료", tip: "주민 배려해서 조용히 관람해주세요" },
      { time: "16:00", duration: "1시간", activity: "전통 찻집에서 한과 + 차", category: "cafe", cost: "약 1.5만원", tip: "차마시는뜰 분위기 최고" },
      { time: "17:30", duration: "1시간", activity: "인사동 거리 구경 + 기념품", category: "shopping", cost: "약 1만원", tip: "쌈지길 안의 독특한 가게들 구경" },
    ],
  },
  {
    id: "course-7",
    title: "제주도 당일치기",
    subtitle: "비행기 타고 제주에서 하루 만끽하기",
    coverGradient: "from-cyan-400 to-blue-500",
    coverEmoji: "🍊",
    area: "제주",
    tags: ["제주", "여행", "프리미엄"],
    rating: 4.9,
    reviewCount: 64,
    price: 5900,
    isPremium: true,
    reviews: [
      { id: "r14", nickname: "시우", rating: 5, comment: "첫 비행기+아침 일찍 출발하면 진짜 알차게 돌 수 있어요! 렌트카 필수", date: "2026-03-22" },
      { id: "r15", nickname: "하린", rating: 5, comment: "성산일출봉 올라가서 본 풍경이 아직도 잊히지 않아요. 꼭 가보세요", date: "2026-02-20" },
    ],
    timetable: [
      { time: "07:00", duration: "1시간 30분", activity: "김포 → 제주 첫 비행기", category: "transport", cost: "약 8만원", tip: "2주 전 예매하면 저렴해요" },
      { time: "09:00", duration: "30분", activity: "렌트카 픽업", category: "transport", cost: "약 5만원", tip: "소형차면 기름값 절약!" },
      { time: "10:00", duration: "2시간", activity: "성산일출봉 등반", category: "activity", cost: "약 5천원", tip: "편한 신발 필수, 물 챙기세요" },
      { time: "12:30", duration: "1시간", activity: "해녀의집에서 해산물 점심", category: "meal", cost: "약 3만원", tip: "성게 비빔밥이 별미!" },
      { time: "14:00", duration: "1시간 30분", activity: "협재해변에서 산책 + 사진", category: "walk", cost: "무료", tip: "에메랄드 바다색이 인생샷 보장" },
      { time: "16:00", duration: "1시간", activity: "한림 카페에서 감귤 주스", category: "cafe", cost: "약 1만원", tip: "카페 델문도 오션뷰 추천" },
      { time: "17:30", duration: "1시간 30분", activity: "흑돼지 거리에서 저녁", category: "meal", cost: "약 4만원", tip: "돔베고기도 꼭 시켜보세요" },
    ],
  },
  {
    id: "course-8",
    title: "이태원/한남동 야경 코스",
    subtitle: "서울의 밤을 가장 아름답게 즐기는 코스",
    coverGradient: "from-indigo-500 to-purple-600",
    coverEmoji: "🌃",
    area: "이태원/한남동",
    tags: ["야경", "로맨틱", "이태원"],
    rating: 4.6,
    reviewCount: 189,
    price: 0,
    isPremium: false,
    reviews: [
      { id: "r16", nickname: "현서", rating: 5, comment: "남산타워 야경이 진짜... 로맨틱 그 자체. 100일 기념 여기 갔는데 대만족", date: "2026-03-19" },
      { id: "r17", nickname: "지아", rating: 4, comment: "블루스퀘어 근처 분위기 좋은 바가 많아요. 조용한 곳 찾으면 추천", date: "2026-03-07" },
    ],
    timetable: [
      { time: "16:00", duration: "1시간", activity: "한남동 디저트 카페에서 시작", category: "cafe", cost: "약 1.5만원", tip: "한남동 테이크아웃 가능한 카페 추천" },
      { time: "17:30", duration: "1시간", activity: "이태원 골목 산책 + 소품샵", category: "walk", cost: "약 1만원", tip: "경리단길 위쪽이 분위기 좋아요" },
      { time: "19:00", duration: "1시간 30분", activity: "이태원 다국적 맛집 디너", category: "meal", cost: "약 4만원", tip: "타코 맛집이나 태국 음식 추천" },
      { time: "21:00", duration: "1시간", activity: "남산타워 야경 감상", category: "culture", cost: "약 2만원", tip: "케이블카보다 걸어 올라가면 운동도 되고 뷰도 최고" },
      { time: "22:30", duration: "1시간 30분", activity: "한남동 와인바에서 마무리", category: "cafe", cost: "약 4만원", tip: "조용한 분위기의 바를 골라주세요" },
    ],
  },
];
