import { CuratedCourse } from "./types";

export const curatedCourses: CuratedCourse[] = [
  {
    id: "course-1",
    title: "성수동 감성 데이트",
    subtitle: "힙한 카페와 갤러리를 돌며 사진 찍기 좋은 코스",
    coverImage: "",
    tags: ["감성", "카페", "사진"],
    rating: 4.8,
    reviewCount: 324,
    price: 0,
    isPremium: false,
    timetable: [
      { time: "11:00", duration: "1시간", activity: "대림창고 갤러리 관람", category: "culture", cost: "무료", tip: "주말엔 줄 서니 오전에 가세요" },
      { time: "12:00", duration: "1시간", activity: "성수 수제버거 맛집", category: "meal", cost: "약 2만원", tip: "어니언 버거 추천" },
      { time: "13:30", duration: "1시간", activity: "카페 오르에르 (루프탑)", category: "cafe", cost: "약 1만원", tip: "루프탑석 일찍 가서 확보" },
      { time: "15:00", duration: "1시간 30분", activity: "서울숲 산책 + 벤치 토크", category: "walk", cost: "무료", tip: "사슴방사장 쪽이 한적해요" },
      { time: "17:00", duration: "1시간", activity: "뚝섬 포토존에서 사진 찍기", category: "photo", cost: "무료" },
    ],
  },
  {
    id: "course-2",
    title: "을지로 레트로 탐험",
    subtitle: "힙지로 감성 뿜뿜, 숨은 맛집과 바 투어",
    coverImage: "",
    tags: ["레트로", "맛집", "밤"],
    rating: 4.6,
    reviewCount: 198,
    price: 0,
    isPremium: false,
    timetable: [
      { time: "14:00", duration: "1시간", activity: "을지로 골목 탐험 + 벽화 사진", category: "walk", cost: "무료", tip: "세운상가 옥상 뷰 추천" },
      { time: "15:30", duration: "1시간", activity: "레트로 다방 커피", category: "cafe", cost: "약 8천원" },
      { time: "17:00", duration: "1시간 30분", activity: "을지로 노포 맛집", category: "meal", cost: "약 2만원", tip: "양미옥 설렁탕 또는 을지면옥" },
      { time: "19:00", duration: "2시간", activity: "을지로 숨은 바 투어", category: "cafe", cost: "약 3만원", tip: "문열기 앞서 줄서야 입장 가능" },
    ],
  },
  {
    id: "course-3",
    title: "한강 피크닉 데이트",
    subtitle: "여유롭게 치킨 시켜놓고 한강 뷰 즐기기",
    coverImage: "",
    tags: ["야외", "피크닉", "힐링"],
    rating: 4.7,
    reviewCount: 456,
    price: 0,
    isPremium: false,
    timetable: [
      { time: "11:00", duration: "30분", activity: "편의점/마트에서 간식 장보기", category: "shopping", cost: "약 2만원", tip: "돗자리는 다이소에서 미리" },
      { time: "11:30", duration: "30분", activity: "여의도 한강공원 자리 잡기", category: "walk", cost: "무료" },
      { time: "12:00", duration: "2시간", activity: "피크닉 + 배달 치킨", category: "meal", cost: "약 2만원", tip: "배달앱에서 한강공원 배달 가능 확인" },
      { time: "14:00", duration: "1시간 30분", activity: "자전거 대여해서 라이딩", category: "activity", cost: "약 6천원", tip: "따릉이 앱 미리 설치" },
      { time: "16:00", duration: "1시간", activity: "선유도 공원 산책", category: "walk", cost: "무료" },
      { time: "17:30", duration: "1시간", activity: "한강 노을 감상", category: "rest", cost: "무료", tip: "해질녘 사진이 인생샷" },
    ],
  },
  {
    id: "course-premium-1",
    title: "프리미엄 오마카세 데이트",
    subtitle: "특별한 날을 위한 풀코스 파인다이닝",
    coverImage: "",
    tags: ["프리미엄", "오마카세", "특별한 날"],
    rating: 4.9,
    reviewCount: 87,
    price: 3900,
    isPremium: true,
    timetable: [
      { time: "16:00", duration: "1시간", activity: "청담동 플라워 카페", category: "cafe", cost: "약 1.5만원" },
      { time: "17:30", duration: "30분", activity: "도산공원 산책", category: "walk", cost: "무료" },
      { time: "18:30", duration: "2시간", activity: "오마카세 디너", category: "meal", cost: "약 15만원", tip: "최소 2주 전 예약 필수" },
      { time: "21:00", duration: "1시간", activity: "루프탑 바에서 야경", category: "cafe", cost: "약 3만원" },
    ],
  },
];
